
splash = false
ipc = true

wallpaper {
    monitor = HDMI-A-1
    # path= /mnt/data/blender_projects/projects/abstract/bigrounds/out/bi1.mp4
    
    # path = /home/spinningdisk/.config/hypr/it-is-done.png
    path = /home/spinningdisk/.config/hypr/celeste.jpg
    # path = /home/spinningdisk/.config/hypr/
    
    # path = /mnt/data/wp.png
}
